## publish npm package using pnpm
name: pnpm Example Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    # configure git user and email
    - name: Configure Git
      run: |
        git config --global user.email "sector.siit@gmail.com"
        git config --global user.name "GitHub Actions"

    - name: Update package.json version
      # Bump the version in package.json using npm version
      run: |
       npm version patch -m "Bump version to %s"
    - name: Install dependencies
      run: pnpm install
    - name: Build and Publish
      run: pnpm publish:npm
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
