name: pnpm Example Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    # configure git user and email
    - name: Configure Git
      run: |
        git config --global user.email "sector.siit@gmail.com"
        git config --global user.name "GitHub Actions"

    - name: Install dependencies
      run: pnpm install

    - name: Bump version and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        npm version patch -m "ci: bump version to %s [skip ci]"
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        echo "New version: $NEW_VERSION"
        git push --follow-tags

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd dist
        npm publish
